### ISSUE TITLE
Errors on update

### ISSUE THREAD

**Issue by agorman** [asticode/go-astisub#42]
```
# go get -u github.com/asticode/go-astisub/...

go: golang.org/x/text upgrade => v0.3.6
go: golang.org/x/net upgrade => v0.0.0-20210410081132-afb366fc7cd1
go: github.com/asticode/go-astits upgrade => v1.8.0
go: github.com/asticode/go-astikit upgrade => v0.20.0
# github.com/asticode/go-astisub
../../../../pkg/mod/github.com/asticode/go-astisub@v0.12.0/teletext.go:338:12: undefined: astits.New
../../../../pkg/mod/github.com/asticode/go-astisub@v0.12.0/teletext.go:357:9: undefined: astits.Data
../../../../pkg/mod/github.com/asticode/go-astisub@v0.12.0/teletext.go:409:26: undefined: astits.Data
../../../../pkg/mod/github.com/asticode/go-astisub@v0.12.0/teletext.go:429:9: undefined: astits.Data
```

**Comment by agorman** [comment]
Looks like the astits interface changed after v1.6.1.

**Comment by asticode** [comment]
Mmmm thing is using `go get -u` will bump dependencies and therefore will make your local version out of sync with correct versions of dependencies to use. I'd recommend not using it otherwise you'll face problems like you are now, which is not an `astisub` problem per se.

Nonetheless, right now it's a good idea to bump `astits` dependency to get the last changes, and I've done just that in the `v0.12.1` tag.

Cheers

**Comment by agorman** [comment]
You're right. I wasn't understanding the `-u` option correctly. Thank you for the response and bumping the version.
