### ISSUE TITLE
vtt file is empty

### ISSUE THREAD

**Issue by dalu** [asticode/go-astisub#8]
trying to read:

https://foxtv-static.ercdn.net/foxtv-subtitle/Kadin/bolumler/33/PDT1KADIN33HDREKLAMLIYENISON.vtt

a downloaded copy.

```go
		filename := "/home/darko/kadinvtt/PDT1KADIN33HDREKLAMLIYENISON.vtt"
		f, e := os.Open(filename)
		if e != nil {
			return e
		}
		f1, e := astisub.ReadFromWebVTT(f)
		if e != nil {
			return e
		}

		fmt.Printf("%q", f1)
		spew.Dump(f1)

		for k, v := range f1.Items {
			fmt.Println(k, v.String())
		}
		return f.Close()
```

```
&{[] %!q(*astisub.Metadata=<nil>) map[] map[]}

(*astisub.Subtitles)(0xc00015a2d0)({
 Items: ([]*astisub.Item) <nil>,
 Metadata: (*astisub.Metadata)(<nil>),
 Regions: (map[string]*astisub.Region) {
 },
 Styles: (map[string]*astisub.Style) {
 }
})
```

Do I have to call anything special?

**Comment by Des-Nerger** [comment]
The above commit fixes the issue. It occured because the implementation checked the first line to be exactly equal to "WEBVTT", not just that the first line start with it (which is what the WebVTT specification mandates, by the way). Your file has the first line "WEBVTT FILE", hence the implementation failed to parse it.

**Comment by dalu** [comment]
I see. I guess it can be closed then. Meanwhile I wrote my own parser with the intention to send the text parts to google translate. Yours is more robust.

**Comment by asticode** [comment]
FYI will be merging the PR in the next few days if you're still looking to use this library
